### PR TITLE
corrected LED order to GRB; corrects M5.dis.drawpix()

### PR DESCRIPTION
**Pull request by hrgraf**
Fixes issue #5 (https://github.com/m5stack/M5Atom/issues/5)

### CODE REVIEW

**Comment by kine90** [comment]
Just manually applied the fix to correct the bug, LED colour works correctly now 
What about merging this request?

**Comment by MFornander** [comment]
It's a pretty messy PR.  A targetted PR with only the required changed would be better IMHO.

**Comment by hrgraf** [comment]
Hi, sorry for the messy PR. It don't know why my further changes have shown up in the PR.
The intended PR should only include the first entry:

"corrected LED order to GRB; corrects M5.dis.drawpix()" 3dd9b5f

that is:
https://github.com/m5stack/M5Atom/pull/29/commits/3dd9b5fbc551e940fdf4883cb4a9d3e88d940a7d

**Comment by Tinyu-Zhao** [comment]
We have solved this problem, thank you for your help!

**Pull request closed without merging**
